name             'systemd_networkd'
maintainer       'Intel Corp'
maintainer_email 'david.m.oneill@intel.com'
license          'All rights reserved'
description      'Installs/Configures systemd_networkd'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'systemd_networkd_fdb'
depends          'systemd_networkd_link'
depends          'systemd_networkd_switchport'
depends          'systemd_networkd_ufd'
depends          'systemd_networkd_team'
